### ISSUE TITLE
Ignore s3 auth?

### ISSUE THREAD

**Issue by kimpepper** [WhoopInc/vagrant-s3auth#13]
If a user has the plugin installed, it will always try and authenticate using credentials. However, if the box is public, then this causes issues, especially if the user has default access keys for a different account.

Is it possible to ignore authentication for requests that just use an https:// url?

**Comment by benesch** [comment]
Yeah, sorry about this. See #10.

I want to continue supporting authentication on HTTPS URLs for backwards compatibility. See [my comment on #10](https://github.com/WhoopInc/vagrant-s3auth/issues/10#issuecomment-78201415) for my proposed fix.

**Comment by benesch** [comment]
Fixed in v1.1.
