### ISSUE TITLE
Support for credentials profiles

### ISSUE THREAD

**Issue by kimpepper** [WhoopInc/vagrant-s3auth#14]
The AWS SDK provides the ability to load credentials from a ~/.aws/credentials file. This provides a more standard approach than the currently recommended method in the README.md

http://docs.aws.amazon.com/AWSSdkDocsRuby/latest//DeveloperGuide/set-up-creds.html

**Comment by benesch** [comment]
I'm fairly certain that if you don't have `AWS_ACCESS_KEY_ID` set in your environment but you do have a default profile in ~/.aws/credentials, those credentials will automatically be loaded. Is this not the case? (If not, ping me and I'll dig in.)

Either way we can definitely add a note to the documentation.

**Comment by benesch** [comment]
And you should be able to choose a profile by setting `AWS_PROFILE`. I'll leave this open until I can verify this behavior works and add a note to the README. (Any chance you'd be able to submit a documentation update PR?)

**Comment by benesch** [comment]
Confirmed that this works. I'll update the documentation and error messages.
