### ISSUE TITLE
Network unreachable error if credentials not found

### ISSUE THREAD

**Issue by companykitchen-dev** [WhoopInc/vagrant-s3auth#15]
I had a configuration problem with my credentials file. This was user error. However, this causes the AWS apis to look for me credentials via the ec2 mechanism that is a hard coded IP and I got a network unreachable error. It would be nice to get a clearer error.

**Comment by benesch** [comment]
I'm unable to reproduce. I get the following error, as expected, when I don't have credentials configured properly:

```
Unable to read AWS credentials from the environment.

Ensure the following variables are set in your environment, or set
them at the top of your Vagrantfile:

    AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY
```

Can you provide more detail on your particular misconfiguration?

**Comment by companykitchen-dev** [comment]
Thanks for looking into it. I run windows and do almost all of my command line stuff via Cygwin. I am using the credentials file approach rather than environment variables. I had placed my credentials file in my windows home directory but Cygwin has it's own home directory. When I moved the credentials file to my Cygwin folder, everything works. I do have the line: #ENV['AWS_PROFILE'] = 'vagrant-s3auth' in my Vagrant file. Is it possible that setting caused it to take a different path that was fully vaidated?

**Comment by benesch** [comment]
Oops, no, I just didn't look hard enough! Looks like it *always* tries to hit the EC2 metadata IP—I've just never run the plugin without internet and so never ran into the issue.

**Comment by benesch** [comment]
Looks like upgrading to v2 of the API (releasing as 1.1 shortly) [will fix it.](https://github.com/aws/aws-sdk-ruby/blob/be0446cb464d92a55987d41487a7762aff490bf2/aws-sdk-core/lib/aws-sdk-core/instance_profile_credentials.rb#L21)

Reopen if that's not the case!
