### ISSUE TITLE
Time Sync must be precise

### ISSUE THREAD

**Issue by companykitchen-dev** [WhoopInc/vagrant-s3auth#16]
The clock on my computer was 1 minute slow. This seemed to cause a forbidden error. It would be nice to have a better check for this. The issue seems to be the S3 signed URL for the box is expired before it starts.

**Comment by benesch** [comment]
Good catch. I'll bump the expiration time from 15s to 5m or so.

**Comment by benesch** [comment]
Fixed in da7f13412237f6. Cheers!
