### ISSUE TITLE
ENV takes precedence over profile setting

### ISSUE THREAD

**Issue by Daemoen** [WhoopInc/vagrant-s3auth#21]
Due to the multiple formats of aws credential storage (boto or "non-boto" ), right now the boto profile specification takes second seat to the active ENV vars.  For many people, this would not make sense.

Take the following situation:
You have both the boto and non boto formats, and dev and production accounts.  You store your production in your active ENV variables since you are constantly working on production in devops.  You set your profile for usage in the Vagrantfile so that you can store the box in your development account.

In this case, the development credentials never get parsed, even if you use the correct profile name for ~/.aws/credentials;  it will always take the active variables from ENV first.

In this case, since the person specified a profile, it makes sense that the profile would take precedence over the ENV vars.

**Comment by benesch** [comment]
You make a good point, but I'm wary of changing the default. I don't want to break backwards compatibility, and I think setting a different order of precedence than the official AWS client library might be equally confusing.

What if vagrant-s3auth just printed out which credential source it was drawing from? Would that help to alleviate the confusion?
