### ISSUE TITLE
s3:// box urls no longer work with vagrant 1.8.1

### ISSUE THREAD

**Issue by nichenke** [WhoopInc/vagrant-s3auth#27]
After upgrading to Vagrant 1.8.1, our private metadata/boxes stopped working.

> $ vagrant box add --name versity/vsm-devtest s3://vsm-dev/vbox/vsm-devtest
> ==> box: Box file was not detected as metadata. Adding it directly...
> ==> box: Adding box 'versity/vsm-devtest' (v0) for provider: virtualbox
>    box: Downloading: s3://vsm-dev/vbox/vsm-devtest

If we change the url to the full https, it starts working again:
> $ vagrant box add https://s3-us-west-2.amazonaws.com/vsm-dev/vbox/vsm-devtest
> ==> box: Loading metadata for box 'https://s3-us-west-2.amazonaws.com/vsm-dev/vbox/vsm-devtest'
>    box: URL: https://vsm-dev.s3-us-west-2.amazonaws.com/vbox/vsm-devtest?X...
> ==> box: Adding box 'versity/vsm-devtest' (v1.2.5) for provider: virtualbox
>    box: Downloading: s3://vsm-dev/vbox/devtest/Versity-info-virtualbox.box

It looks like something is missing the s3:// url munging. This change to https:// urls seems to work for us with Vagrant 1.7.4 as well, so we are going to push Vagrantfile changes to work around this for now.

**Comment by benesch** [comment]
Urgh. That's what I get for relying on private API.

Laptop's in the shop until next week, but this in this month's queue. Unless, of course, you find some bandwidth to submit a PR!

**Comment by benesch** [comment]
Agh. https://github.com/mitchellh/vagrant/commit/891c47c7423c8ddc2aef2f400dd7d124188a5dd4

**Comment by benesch** [comment]
Fix released in v1.3.0. Thanks for reporting!
