### ISSUE TITLE
`to_json': wrong argument type JSON::Pure::Generator::State (expected JSON/Generator/State) 

### ISSUE THREAD

**Issue by bantonj** [WhoopInc/vagrant-s3auth#29]
When running vagrant up I get the error in the gist below.

https://gist.github.com/bantonj/4c197e84c3f6a0846146089bcaadfe4a

This looks related to an issue in aws-sdk-ruby listed below.

https://github.com/aws/aws-sdk-ruby/issues/1150

It looks like pinning the aws-sdk-ruby to the newest version should fix this issue.

**Comment by waisbrot** [comment]
Thanks for diagnosing. Would you like to make a PR for this?

**Comment by bantonj** [comment]
Looking into this more deeply it looks like just uninstalling and reinstalling will grab a newer version of jmespath, which fixes the issue.
